### ISSUE TITLE
FreePBX 12 not compatable

### ISSUE THREAD

**Issue by meluvalli** [FreePBX/hotelwakeup#62]
After removing 2.11.3 and upgrading to Beta, kills FreePBX totally.  Only get ERROR 500 page when trying to access FreePBX.   Had to remove to fix it.

I am running PBX In A Flash Black.

**Comment by laptopu** [comment]
I am running Asterisk 11.12.0 FreePBX 2.11.0.34 and think this problem is related to the PHP issue too.  Running 2.11.3 wakeup calls.

When setting a wake up call for the first time, expected behaviour:
'Please enter the time for your wake-up call' <enter time> 'press 1 for am, 2 for pm' <enter 1 or 2> 'you have requested a wake-up call for xx:xx(am/pm). Goodbye'. Line clears.

Actual behaviour:
'Please enter the time for your wake-up call' <enter time> 'press 1 for am, 2 for pm' <enter 1 or 2> 'you have requested a wake-up call for xx:xx(am/pm)'. Line clears.

When dialling *68 after a wake up call has been set, expected behaviour:
'You have requested a wake-up call for xx:xx(am/pm)' then options to change the wake-up call.

Actual behaviour:
'You have requested a wake-up call for xx:xx(am/pm)' line clears.

I tried removing 2.11.3 and upgraded to the latest beta as the functionality sounded great but this broke my FreePBX access from a browser. I would love this to be resolved and ideally for the new features in the beta to work with my setup, it is a big part of my system at home and would be really appreciated, I know you guys are not paid for this work but any update on it would be great thanks.
